# -*- coding: utf-8 -*-
<<<<<<< HEAD
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields
from django.conf import settings
=======
# Generated by Django 1.9.5 on 2016-04-14 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields
>>>>>>> bc042a494fbe202ab96728572e9ee47abb267825


class Migration(migrations.Migration):

<<<<<<< HEAD
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
    initial = True

    dependencies = [
>>>>>>> bc042a494fbe202ab96728572e9ee47abb267825
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> bc042a494fbe202ab96728572e9ee47abb267825
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.CharField(max_length=100)),
                ('instruction', redactor.fields.RedactorField(verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(to='exam.Category', blank=True)),
                ('creator', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instruction', redactor.fields.RedactorField(verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Category')),
>>>>>>> bc042a494fbe202ab96728572e9ee47abb267825
            ],
        ),
    ]
