# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 17:59
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manychoiceanswer',
            name='text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82'),
        ),
    ]
