# -*- coding: utf-8 -*-
<<<<<<< HEAD
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
=======
# Generated by Django 1.9.5 on 2016-04-14 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> bc042a494fbe202ab96728572e9ee47abb267825


class Migration(migrations.Migration):

<<<<<<< HEAD
=======
    initial = True

>>>>>>> bc042a494fbe202ab96728572e9ee47abb267825
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivationKey',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('activation_key', models.CharField(max_length=100)),
                ('key_expires', models.DateTimeField()),
                ('user', models.OneToOneField(related_name='saveuser', to=settings.AUTH_USER_MODEL)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=100)),
                ('key_expires', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saveuser', to=settings.AUTH_USER_MODEL)),
>>>>>>> bc042a494fbe202ab96728572e9ee47abb267825
            ],
        ),
    ]
